USE hotel_db;
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO rooms (available, createdAt, updatedAt) VALUES (true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO tables (name, phone, email, res_time, num_party,available, createdAt, updatedAt) VALUES ("", 9999999, "", "", 0 ,false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);





